# Schema for the configuration files of the Form Protect module.

form_protect.settings:
  type: config_object
  label: 'Form Protect settings'
  mapping:
    form_ids:
      type: sequence
      label: 'Form IDs'
      sequence:
        type: string
        label: 'Form ID'
    log:
      type: boolean
      label: 'Log blocked submits'
