# Schema for the configuration files of the Consent Manager module.

consent_manager.settings:
  type: config_object
  label: 'Consent Manager Settings'
  mapping:
    blocking_mode:
      type: string
      label: 'Blocking mode'
    cdid:
      type: string
      label: 'Code-ID'
    host:
      type: string
      label: 'Host'
    cdn:
      type: string
      label: 'CDN'
    custom_code:
      type: string
      label: 'Custom HTML code'
