_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: pl
uuid: 6dd80d4e-cb9a-46ef-b8f4-c03b9335439c
name: Wolontariat
mail: admini@sgh.waw.pl
slogan: ''
page:
  403: ''
  404: ''
  front: /node/242
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
